name: Github checks

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
    - main
    paths:
    - 'app/**'

jobs:
  github-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2    
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: app/package-lock.json
    - name: Install dependencies
      working-directory: ./app
      run: npm ci
    - name: Check formatting
      working-directory: ./app
      run: npm run format:ci
    - name: Run tests
      working-directory: ./app
      run: npm run test:ci
